Added matcher to allow proper date matching in unit tests
ONSdigital/rm-common-test-framework pull request #3
Opened 2018-01-26 12:48 UTC by madeye-matt

Previously many of the endpoint unit tests used string comparisons to compare dates.  This is obviously brittle as any difference in the format, timezone etc of the string will cause a failure even through the dates are actually the same.   This PR adds a DateMatcher that makes it possible to compare the dates in the unit tests instead of the strings

2018-01-26 15:44 UTC, benjefferies requested changes

2018-01-26 15:44 UTC, benjefferies commented on pom.xml
> +      <version>10.49.7-SNAPSHOT</version>
Should be bumped to the release version

2018-01-29 11:04 UTC, benjefferies approved these changes

2018-01-29 11:19 UTC, davidmort approved these changes

2018-01-29 11:19 UTC, merged